package transactions

type TxType string

const (
	AccountDeleteTx                     TxType = "AccountDelete"
	AccountSetTx                        TxType = "AccountSet"
	AMMBidTx                            TxType = "AMMBid"
	AMMClawbackTx                       TxType = "AMMClawback"
	AMMCreateTx                         TxType = "AMMCreate"
	AMMDeleteTx                         TxType = "AMMDelete"
	AMMDepositTx                        TxType = "AMMDeposit"
	AMMVoteTx                           TxType = "AMMVote"
	AMMWithdrawTx                       TxType = "AMMWithdraw"
	BatchTx                             TxType = "Batch"
	CredentialAcceptTx                  TxType = "CredentialAccept"
	CredentialCreateTx                  TxType = "CredentialCreate"
	CredentialDeleteTx                  TxType = "CredentialDelete"
	CheckCancelTx                       TxType = "CheckCancel"
	CheckCashTx                         TxType = "CheckCash"
	CheckCreateTx                       TxType = "CheckCreate"
	ClawbackTx                          TxType = "Clawback"
	DepositPreauthTx                    TxType = "DepositPreauth"
	DelegateSetTx                       TxType = "DelegateSet"
	DIDDeleteTx                         TxType = "DIDDelete"
	DIDSetTx                            TxType = "DIDSet"
	EscrowCancelTx                      TxType = "EscrowCancel"
	EscrowCreateTx                      TxType = "EscrowCreate"
	EscrowFinishTx                      TxType = "EscrowFinish"
	LedgerStateFixTx                    TxType = "LedgerStateFix"
	MPTokenAuthorizeTx                  TxType = "MPTokenAuthorize"
	MPTokenIssuanceCreateTx             TxType = "MPTokenIssuanceCreate"
	MPTokenIssuanceDestroyTx            TxType = "MPTokenIssuanceDestroy"
	MPTokenIssuanceSetTx                TxType = "MPTokenIssuanceSet"
	NFTokenAcceptOfferTx                TxType = "NFTokenAcceptOffer"
	NFTokenBurnTx                       TxType = "NFTokenBurn"
	NFTokenCancelOfferTx                TxType = "NFTokenCancelOffer"
	NFTokenCreateOfferTx                TxType = "NFTokenCreateOffer"
	NFTokenMintTx                       TxType = "NFTokenMint"
	NFTokenModifyTx                     TxType = "NFTokenModify"
	OfferCancelTx                       TxType = "OfferCancel"
	OfferCreateTx                       TxType = "OfferCreate"
	OracleDeleteTx                      TxType = "OracleDelete"
	OracleSetTx                         TxType = "OracleSet"
	PaymentTx                           TxType = "Payment"
	PaymentChannelClaimTx               TxType = "PaymentChannelClaim"
	PaymentChannelCreateTx              TxType = "PaymentChannelCreate"
	PaymentChannelFundTx                TxType = "PaymentChannelFund"
	PermissionedDomainDeleteTx          TxType = "PermissionedDomainDelete"
	PermissionedDomainSetTx             TxType = "PermissionedDomainSet"
	SetRegularKeyTx                     TxType = "SetRegularKey"
	SignerListSetTx                     TxType = "SignerListSet"
	TicketCreateTx                      TxType = "TicketCreate"
	TrustSetTx                          TxType = "TrustSet"
	XChainAccountCreateCommitTx         TxType = "XChainAccountCreateCommit"
	XChainAddAccountCreateAttestationTx TxType = "XChainAddAccountCreateAttestation"
	XChainAddClaimAttestationTx         TxType = "XChainAddClaimAttestation"
	XChainClaimTx                       TxType = "XChainClaim"
	XChainCommitTx                      TxType = "XChainCommit"
	XChainCreateBridgeTx                TxType = "XChainCreateBridge"
	XChainCreateClaimIDTx               TxType = "XChainCreateClaimID"
	XChainModifyBridgeTx                TxType = "XChainModifyBridge"
)
